//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public int GenreId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
